---
name: Hetzner DNS DDNS
version: "1.0.3"
slug: hcloud-ddns
description: Automatically update DNS records via Hetzner DNS API
url: https://github.com/prindom/hcloud-ddns
init: false
ingress: true
ingress_port: 8099
arch:
  - aarch64
  - amd64
options:
  api_key: "1234513256"
  zone_id: "35412345443"
  domain: "test.example.com"
  update_interval: "hourly"
  dry_run: true
  log_level: "info"
schema:
  api_key: password
  zone_id: str
  domain: str
  update_interval: list(hourly|daily|weekly)
  dry_run: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)
